### ISSUE TITLE
support sql dumps import

### ISSUE THREAD

**Issue by rokde** [ipunkt/rancherize#16]
Support - like nginx_snippets - a list of sql dump files to provision a newly generated database.

Simply import given filename.

The container for mysql does support it automatically by following configuration:
```yaml
services:
  Database:
    image: 'ipunktbs/mysql-master:v1'
    tty: true
    volumes:
      - './public/db.sql:/docker-entrypoint-initdb.d/init.sql'
```

Any sql file in `/docker-entrypoint-initdb.d` will be imported during startup.
