### ISSUE TITLE
Laravel Queue Worker über Webserver Blueprint aktivieren

### ISSUE THREAD

**Issue by justb81** [ipunkt/rancherize#3]

**Comment by rokde** [comment]
```yaml
QueueWorker:
  image: 'ipunktbs/laravel-queue-worker:latest'
  environment:
    APP_ENV: local
    APP_DEBUG: '1'
    QUEUE_CONNECTION: redis
    QUEUE_NAME: default
  volumes:
    - '/var/workspaces/laravel-application-root:/var/www/app'
  links:
    - 'Redis:redis'
    - 'Database:database-master'
  restart: unless-stopped
```
